version: '3.5'
services:
  milvus:
    image: milvusdb/milvus:v2.4.0
    container_name: milvus
    restart: unless-stopped
    environment:
      - ETCD_USE_EMBED=true
      - MILVUS_LOG_LEVEL=info
    ports:
      - '19530:19530' # Milvus gRPC
      - '9091:9091' # Milvus HTTP
    volumes:
      - milvus_data:/var/lib/milvus
volumes:
  milvus_data:
